networks:
  archon:
    external: true

services:
  archon_api:
    build: .
    container_name: archon_api
    networks:
      archon:
        ipv4_address: 10.247.92.10
    ports:
      - ${API_PORT}:80
    expose:
      - 80
    environment:
      - "TWITCH_KEY=${TWITCH_KEY}"

  archon_db:
    image: mongo
    container_name: archon_db
    networks:
      archon:
        ipv4_address: 10.247.92.11
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ${DATA_ROOT}/db:/data/db
    expose:
      - 27017
